model:
  scd: /vol/work/lerner/allies/baseline/scd/train/ALLIES.SpeakerDiarization.Custom.train/validate_segmentation_fscore/ALLIES.SpeakerDiarization.Custom.development/apply/0941
  emb: /vol/work/lerner/allies/baseline/arcface+variable/train/ALLIES.SpeakerDiarization.Custom.train/validate_diarization_fscore/ALLIES.SpeakerDiarization.Custom.development/apply/0014/

identification:
  subsets:
    - train
    - development
  label_min_duration: 0.0
  weigh: True
  classifier:
    k: 5
    threshold: 0.1
pipeline:
   name: pyannote.audio.pipeline.speaker_diarization.SpeakerDiarization
   params:
      sad_scores: oracle
      scd_scores: /vol/work/lerner/allies/baseline/scd/train/ALLIES.SpeakerDiarization.Custom.train/validate_segmentation_fscore/ALLIES.SpeakerDiarization.Custom.development/apply/0941
      embedding: /vol/work/lerner/allies/baseline/arcface+variable/train/ALLIES.SpeakerDiarization.Custom.train/validate_diarization_fscore/ALLIES.SpeakerDiarization.Custom.development/apply/0014/
      metric: cosine
      method: average
      evaluation_only: True
sampler:
   name: TPESampler

loss: 0.13051666826632252
params:
  min_duration: 0.4381704929101738
  speech_turn_assignment:
    closest_assignment:
      threshold: 1.1119680622237293
  speech_turn_clustering:
    clustering:
      threshold: 0.19468240749530696
  speech_turn_segmentation:
    speaker_change_detection:
      alpha: 4.3199666907123714e-05
      min_duration: 1.626668986940032
    speech_activity_detection: {}

