model:
  emb: /vol/work/lerner/allies/baseline/arcface+variable/train/ALLIES.SpeakerDiarization.Custom.train/validate_diarization_fscore/ALLIES.SpeakerDiarization.Custom.development/
  scd: /vol/work/lerner/allies/baseline/scd/train/ALLIES.SpeakerDiarization.Custom.train/validate_segmentation_fscore/ALLIES.SpeakerDiarization.Custom.development/

pipeline:
   name: pyannote.audio.pipeline.speaker_diarization.SpeakerDiarization
   params:
      sad_scores: oracle
      scd_scores: /vol/work/lerner/allies/baseline/scd/train/ALLIES.SpeakerDiarization.Custom.train/validate_segmentation_fscore/ALLIES.SpeakerDiarization.Custom.development/apply/0941
      embedding: /vol/work/lerner/allies/baseline/arcface+variable/train/ALLIES.SpeakerDiarization.Custom.train/validate_diarization_fscore/ALLIES.SpeakerDiarization.Custom.development/apply/0014/
      metric: cosine
      method: affinity_propagation
      evaluation_only: True
sampler:
   name: TPESampler

loss: 0.16090632896238663
params:
  min_duration: 0.6341458378859106
  speech_turn_assignment:
    closest_assignment:
      threshold: 0.597488494577604
  speech_turn_clustering:
    clustering:
      damping: 0.8110575610241849
      preference: -4.191155431705313
  speech_turn_segmentation:
    speaker_change_detection:
      alpha: 4.3199666907123714e-05
      min_duration: 1.626668986940032
    speech_activity_detection: {}
